### ISSUE TITLE
For which leica product has been developed?

### ISSUE THREAD

**Issue by ineslara21** [manuoso/pub_leica#1]
Hi! 
I would like to know in which product from leica have been this code tested?

Thanks

**Comment by manuoso** [comment]
Hello! This code was used to test the total station ms50 but it is simply a data receiver that provides the computer that was connected to the leica and is then published in ROS!
The Leica control code is private in the GRVC repository.
Thank you ines! 

PD: el código es horroroso y super mal programado, que era lo primero que casi hice cuando empecé a trabajar jajaja. Si te interesa más lo de cómo sacar la info de la posición del prisma de la Leica le puedes pedir mi número a Marco o a Fidel (que trabaja contigo). Un saludo!
